### ISSUE TITLE
flutter test - Error: The non-abstract class '_MockHttpRequest' is missing implementations for these members

### ISSUE THREAD

**Issue by AbrarPeer** [bitrise-steplib/bitrise-step-flutter-test#11]
Hi Im getting an issue with this step where it suddenly is failing.

I'm not sure what I should be doing to resolve it.

The last time it ran successfully was 2020.09.20 @ 22:51

Appreciate your guidance.

Thanks

PS for the moment I am skipping this step.

```
+------------------------------------------------------------------------------+

| (8) flutter-test@0                                                           |
+------------------------------------------------------------------------------+
| id: flutter-test                                                             |
| version: 0.10.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-10-07T23:56:18Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AdditionalParams: 
- ProjectLocation: .
- TestResultsDir: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results329746079/test_result455756161
- GenerateCodeCoverageFiles: true
Running test
Command `tojunit` not found, installing...
$ flutter "pub" "global" "activate" "junitreport"
Resolving dependencies...
+ args 1.6.0
+ charcode 1.1.3
+ collection 1.14.13
+ convert 2.1.1
+ intl 0.16.1
+ junitreport 1.3.1
+ meta 1.2.3
+ path 1.7.0
+ petitparser 3.1.0
+ testreport 1.2.0
+ typed_data 1.2.0
+ xml 4.5.1
Downloading junitreport 1.3.1...
Downloading testreport 1.2.0...
Downloading meta 1.2.3...
Precompiling executables...
Precompiled junitreport:tojunit.
Installed executable tojunit.
Activated junitreport 1.3.1.
$ flutter "test" "--machine" | tojunit "--output" "./flutter_junit_test_results.xml"
Waiting for another flutter command to release the startup lock...
                                                                  
../../Library/flutter/packages/flutter_test/lib/src/_binding_io.dart:208:7: Error: The non-abstract class '_MockHttpRequest' is missing implementations for these members:
 - HttpClientRequest.abort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
class _MockHttpRequest extends HttpClientRequest {
      ^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:2045:8: Context: 'HttpClientRequest.abort' is defined here.
  void abort([Object? exception, StackTrace? stackTrace]);
       ^^^^^
Completing test command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flutter-test@0 (exit code: 1)                                 | 27.00 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ithub.com/bitrise-steplib/bitrise-step-flutter-test/issues |
| Source: https://github.com/bitrise-steplib/bitrise-step-flutter-test         |
+---+---------------------------------------------------------------+----------+
```

**Comment by bitce** [comment]
Hi @AbrarPeer! Can you please send us a link to a build here and enable Support user access in the Settings?

**Comment by AbrarPeer** [comment]
Hi Bence,

I have toggled the switch as requested.

The link to our latest build log is https://app.bitrise.io/build/38351ac056b1c67d#?tab=log
[https://www.bitrise.io/assets/placeholders/website-social-embed.png]<https://app.bitrise.io/build/38351ac056b1c67d#?tab=log>
Bitrise - Mobile Continuous Integration and Delivery<https://app.bitrise.io/build/38351ac056b1c67d#?tab=log>
Android, iOS & cross-platform mobile continuous integration / delivery, with 200+ integrations. Sign up and start building (for free!) today.
app.bitrise.io


Regards


Regards

Abrar Peer

Mobile Team Lead


[Arq Group]

M  +61 4 2121 7337

E   abrar.peer@arq.group<mailto:tristan.sternson@arq.group>

A   Level 3, 192 Ann St, Brisbane, QLD, 4000

arq.group<http://www.arq.group/>


________________________________

**Comment by mjones-droid** [comment]
Hey @AbrarPeer!

It looks like your last green build used Flutter 1.20.2. The first red build shows that it was using Flutter 1.20.3. Since nothing else changed with your project, I'm guessing this problem is related to the Flutter upgrade. 

Let's try rolling back the Flutter version to see if that clears the error. After your Flutter Install step, add a script step with the following line to downgrade.

`flutter version 1.20.2`

If that works, then we know for sure the Flutter version is the issue. That means either there's an issue with your project config or there's a bug in that particular version of flutter. 

It looks like the latest stable version (released yesterday) is 1.22.1, so it might also be worth upgrading to that version to see if it clears the error.

**Comment by AbrarPeer** [comment]
Hi All,

I can confirm that locking flutter to the legacy version resolves the issue.

We have to evaluate whether this is sustainable for the long term however for now this is acceptable for our project.


Regards

Abrar Peer

Mobile Team Lead


[Arq Group]

M  +61 4 2121 7337

E   abrar.peer@arq.group<mailto:tristan.sternson@arq.group>

A   Level 3, 192 Ann St, Brisbane, QLD, 4000

arq.group<http://www.arq.group/>

________________________________

**Comment by adminGC** [comment]
any update for this issue? @AbrarPeer

**Comment by gofur** [comment]
hi @AbrarPeer, any update for this issue?
