### ISSUE TITLE
Flutter Test results only uploaded if all tests pass.

### ISSUE THREAD

**Issue by kvanry** [bitrise-steplib/bitrise-step-flutter-test#13]
During this build, the tests don't all pass, as such, it appears that no test results are available to see what tests failed.

https://app.bitrise.io/build/7598995e190525d4

However, if you look at this successful build the test results do show. 

https://app.bitrise.io/build/7170b905ef6508a4

The only difference between these 2 builds is that in the second all tests pass, in the first one test fails.

**Comment by bitce** [comment]
Hi @kvanry! Thanks for the report, it seems to be accurate. Can you enable Support User access in the Settings for is so we can take a more in-depth look? :)

**Comment by kvanry** [comment]
@bitce I have enabled support user access for you. Thanks for looking into this!

**Comment by mjones-droid** [comment]
Hey @kvanry!

I've confirmed that this is a bug with our Flutter Test step and have filed a bug report with the dev's. Thanks for bringing it to our attention.

**Comment by drekka** [comment]
I seem to be having this issue too. Any idea what the problem is?

**Comment by maxlapides** [comment]
@mjones-droid Is there any update on this issue?

**Comment by mjones-droid** [comment]
Hey @maxlapides. Not at this time. :( A bug report has been filed and I believe it's planned for an upcoming sprint.
