### ISSUE TITLE
flutter test command executed multiple times with coverage report

### ISSUE THREAD

**Issue by Sese-Schneider** [bitrise-steplib/bitrise-step-flutter-test#25]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.x.x
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

IMO this is a general flow issue of the test step.
When executing it with **coverage generation _enabled_**, `flutter test` essentially executes twice.

- The first time as usual when running a test
- A second time to run it with the argument `--coverage`.

As tests and testing with coverage right now takes a very long time on large projects (see https://github.com/dart-lang/sdk/issues/45985), removing the first run could cut down the time needed to execute the step _significantly_.

This would reduce the time needed for this step on our project from ~45min to around 30min

I think changing the execution to only run `flutter test` once could be a quick and easy modification to the `main.go` file.
I currently can't contribute to the project, but might open a PR in the future, if this isn't addressed.

### Bitrise info

- Build URL: https://app.bitrise.io/build/a258e8b7f48e2ce5
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
+---+---------------------------------------------------------------+----------+
| ✓ | flutter-test@1                                                | 43.1 min |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. Create a flutter project with a lot of tests and files for coverage.
2. Run the flutter test step on it with coverage generation enabled.

**Comment by Roland-Bak** [comment]
Hello @Sese-Schneider 👋

I forwarded your findings to the developers, hopefully this will get addressed soon!  🙂
