### ISSUE TITLE
Test step failing with no information on why

### ISSUE THREAD

**Issue by cadaniel** [bitrise-steplib/bitrise-step-flutter-test#26]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.0.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NO 

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Flutter test is failing without error messages or test reports. Running flutter test on my local machine has all tests passing. Flutter analyize has no such problem. It's able to compile and ![Screen Shot 2021-08-03 at 10 20 32 AM](https://user-images.githubusercontent.com/5515671/128050888-27a59434-bd8a-41e2-b56b-2cc9a16cf1cb.png) the source code before running tests. 

![Screen Shot 2021-08-03 at 10 16 01 AM](https://user-images.githubusercontent.com/5515671/128050324-1c7ae7f9-c303-43cd-8a32-0ab589df7978.png)

![Screen Shot 2021-08-03 at 10 20 32 AM](https://user-images.githubusercontent.com/5515671/128050888-27a59434-bd8a-41e2-b56b-2cc9a16cf1cb.png)

### Bitrise info

- Build URL: _Please share the build URL with us._ https://app.bitrise.io/build/10867bf0-9109-4ce4-a84e-b47dcb078332#?tab=artifacts
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled:  YES 
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+
| (7) flutter-test@1                                                           |
+------------------------------------------------------------------------------+
| id: flutter-test                                                             |
| version: 1.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-08-03T16:01:23Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AdditionalParams: 
- TestsPathPattern: 
- ProjectLocation: /Users/vagrant/git
- TestResultsDir: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results773993859/test_result173643639
- GenerateCodeCoverageFiles: false
Running test
Command `tojunit` not found, installing...
$ flutter "pub" "global" "activate" "junitreport"
Resolving dependencies...
+ args 1.6.0 (2.2.0 available)
+ charcode 1.3.1
+ collection 1.15.0
+ convert 2.1.1 (3.0.1 available)
+ intl 0.16.1 (0.17.0 available)
+ junitreport 1.3.1
+ meta 1.7.0
+ path 1.8.0
+ petitparser 3.1.0 (4.2.0 available)
+ testreport 1.2.0
+ typed_data 1.3.0
+ xml 4.5.1 (5.1.2 available)
Downloading junitreport 1.3.1...
Downloading testreport 1.2.0...
Downloading intl 0.16.1...
Downloading charcode 1.3.1...
Downloading meta 1.7.0...
Precompiling executables...
Precompiled junitreport:tojunit.
Installed executable tojunit.
Activated junitreport 1.3.1.
$ flutter "test" "--machine" | tojunit "--output" "flutter_junit_test_results.xml"
Completing test command failed, error: exit status 1
test results exported in junit format successfully
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flutter-test@1 (exit code: 1)                                 | 2.5 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ithub.com/bitrise-steplib/bitrise-step-flutter-test/issues |
| Source: https://github.com/bitrise-steplib/bitrise-step-flutter-test         |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. run tests

**Comment by allene-norton-bitrise** [comment]
Hi @cadaniel - in order for test artifacts to be attached to the build, you will need to add the Deploy to Bitrise step after your Flutter Test step. Please try this and if this is not helpful, please link the new build.

Thanks!

**Comment by cadaniel** [comment]
So I was able to remote into a machine to find the failing test. I'm working on a fix for it now and will test again.

But I'm sure you can see why this is still a problem. I don't want to create a build every time I just need unit tests run. As a user, I would still expect tests reports to be available for download. Every other CI/CD service I've used does this.
