### ISSUE TITLE
No active package junitreport.

### ISSUE THREAD

**Issue by bakua** [bitrise-steplib/bitrise-step-flutter-test#34]
### Troubleshooting

Hello, 

I am running into the following issue where my builds timeout due to flutter test plugin:

```
+------------------------------------------------------------------------------+

| (7) flutter-test@1                                                           |
+------------------------------------------------------------------------------+
| id: flutter-test                                                             |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-12-26T01:02:57Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AdditionalParams: 
- TestsPathPattern: 
- ProjectLocation: .
- TestResultsDir: /var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/test_results353407940/test_result884624230
- GenerateCodeCoverageFiles: false
```
...
```
No active package junitreport.
timeout after 2700 seconds
```

Build URL: https://app.bitrise.io/build/c2d2a62c-1315-457b-86db-ff885bff2dda#?tab=log
I am using Flutter 2.8.1 stable.

Thank you

**Comment by patrickhammond** [comment]
We are also experiencing the same issue.

**Comment by patrickhammond** [comment]
Adding `pub global activate junitreport` to a script step before the flutter-test step seems to address the issue for us.

**Comment by doc-rj-celltrak** [comment]
Thanks @patrickhammond, the workaround helps. Now who's breaking out their Golang skills to fix this step? :P

**Comment by ofalvai** [comment]
Hey everyone 👋 Thank you for raising this issue, we decided to preinstall the `junitreport` package to the build VMs. This is not live yet, but will be included in the next VM image update rollout.

**Comment by khanguyen88** [comment]
@ofalvai Did the VM change roll out today? All of my builds got stuck at ``flutter test`` for a couple of hours with this message.

![Screen Shot 2022-04-13 at 5 06 43 PM](https://user-images.githubusercontent.com/26890183/163155299-da674b55-48bb-498c-bc15-06e92673970e.png)

Applying the suggested command fixed the issue, but maybe this step should fail or timeout instead of hanging.

**Comment by ofalvai** [comment]
@khanguyen88 it's weird, the suggested command is exactly what we are running to activate `junitreport`. Just to double-check, did running the command in the workflow resolve the hanging build?

**Comment by koishi** [comment]
I had same problem, but solved it by adding the following script before execution.
`dart pub global activate junitreport`
