### ISSUE TITLE
Flutter Test output not loadable in Test Report

### ISSUE THREAD

**Issue by ihancock** [bitrise-steplib/bitrise-step-flutter-test#36]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.0.2
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

The output from this does not appear to work in Test Report. Looking at the JSON artifact for the tests, it appears that the output from a pub get is on the first line: -

Running "flutter pub get" in src...                                24.5s
{"protocolVersion":"0.1.1","runnerVersion":"1.19.5","pid":2198,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/bitrise/src/test/process_chrome_options_test.dart"},"type":"suite","time":1}
.
.
.

However I have added a step to remove this line which is successful but on clicking the Test Report add on it is still not able to open the report, giving the following error: -

Test Reports wasn't configured correctly. Please make sure you configure it in the Workflow Editor. [Get help for setting up Test Reports.](https://devcenter.bitrise.io/testing/test-reports/)

### Bitrise info

- Build URL: https://app.bitrise.io/build/8111d88e-0b46-4355-8d00-34e61627f8bf?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES 
- Log: 

<details>
  <pre>
N/A
  </pre>
</details>

### Steps to reproduce

1. Run Primary flow
2. Click on add on Test Report

**Comment by ofalvai** [comment]
Hey @ihancock, you can see the actual error in the output of the Deploy to Bitrise.io step:

```
Upload test results
error during parsing test results: %!(EXTRA *errors.withStack=XML syntax error on line 72: illegal character code U+001B:
```

Looking at the printed XML contents, it's indeed an illegal character code coming from the terminal control sequences used for colored terminal output: https://www.fileformat.info/info/unicode/char/001b/index.htm

I think it should be handled by the `junitreport` package, I suggest raising this in their issue tracker.

**Comment by ofalvai** [comment]
I agree, but the encoding is done by `tojunit`, this step calls it the following way:

```
$ flutter "test" "--machine" "--coverage" | tojunit "--output" "flutter_junit_test_results.xml"
```
