### ISSUE TITLE
flutter-test fails with New Flutter v3.7.1

### ISSUE THREAD

**Issue by workerbee22** [bitrise-steplib/bitrise-step-flutter-test#41]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.0.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description

When using newest version:

```
Flutter 3.7.1
Dart 2.19.1
```

flutter-est step v1.0.2 (latest) fails every time with error:

```
Running test
$ flutter "test" "--machine" | tojunit "--output" "flutter_junit_test_results.xml"
Could not find a file named "pubspec.yaml" in "/Users/vagrant/.pub-cache/hosted/pub.dev/junitreport-2.0.2".
```

### Bitrise info

- Build URL: https://app.bitrise.io/build/9f56f317-53a5-480d-aece-fd10a58c2248
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>

+------------------------------------------------------------------------------+

| (7) Flutter Test                                                             |
+------------------------------------------------------------------------------+
| id: flutter-test                                                             |
| version: 1.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2023-02-04T02:24:16Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- additional_params: <unset>
- tests_path_pattern: <unset>
- project_location: .
- bitrise_test_result_dir: /var/folders/9l/1ysg9vq51p37q0lgksxhdb9r0000gn/T/test_results4080150439/test_result3248266612
- generate_code_coverage_files: false
Running test
$ flutter "test" "--machine" | tojunit "--output" "flutter_junit_test_results.xml"
Could not find a file named "pubspec.yaml" in "/Users/vagrant/.pub-cache/hosted/pub.dev/junitreport-2.0.2".
Task was aborted

  </pre>
</details>

**Comment by tzuhan-bitrise** [comment]
Hi there,

I'm Han from the technical support engineer team of Bitrise and I'm happy to assist.
We've multiple customers reporting this issue which is introduced by the latest Flutter release (3.7.1)
Currently, the workaround is to reactive the junitreport package globally before running the flutter test.

Here's the solution:
- Add a **script** step before the **flutter-test** step
- reactivate the junitreport by this command: ```flutter pub global activate junitreport```

Please let me know if you have any questions!

Best,
Han

**Comment by tomk9** [comment]
Now with `Flutter 3.7.5` tests work again!
